### ISSUE TITLE
find error

### ISSUE THREAD

**Issue by SkullFang** [emanuele/minibatch_kmeans#1]
in kmeans.py 
the line 39:
X_batch = X[b*t:b*(t+1)]

the code 
maybe is 

X_batch = X[b*i:b*(i+1)]

right?

**Comment by emanuele** [comment]
You are right! Thank you for spotting the bug. The difference in the result with and without the bug is not big - at least in the simple tests included in the code. I'm fixing the code right now. Thanks again.
